#!/usr/bin/env bash
set -euo pipefail

# Usage: kcluster <check|create|start|stop>

PROJECT_ROOT="$(dirname "$(realpath "$0")")"
source "$PROJECT_ROOT/scripts/common.sh"
source "$PROJECT_ROOT/config.env"
SCRIPT="$PROJECT_ROOT/scripts/${1:-}.sh"

if [[ $# -eq 0 || ! -f "$SCRIPT" ]]; then
    echo "Usage: kcluster <check|create|start|stop>"
    exit 1
fi

shift
bash "$SCRIPT" "$@"
